import {
    Folder,
    BookOpen,
    GraduationCap,
    Briefcase,
    Target,
    Star,
    Flame,
    Lightbulb,
    Rocket,
    BookMarked,
    Sparkles,
    Palette,
    Globe,
    Music,
    Code2,
    Microscope,
    type LucideIcon,
} from "lucide-react";

export const FOLDER_ICONS: { name: string; label: string; Icon: LucideIcon }[] = [
    { name: "Folder",        label: "Thư mục",    Icon: Folder },
    { name: "BookOpen",      label: "Sách mở",    Icon: BookOpen },
    { name: "GraduationCap", label: "Tốt nghiệp", Icon: GraduationCap },
    { name: "Briefcase",     label: "Công việc",  Icon: Briefcase },
    { name: "Target",        label: "Mục tiêu",   Icon: Target },
    { name: "Star",          label: "Nổi bật",    Icon: Star },
    { name: "Flame",         label: "Hot",         Icon: Flame },
    { name: "Lightbulb",     label: "Ý tưởng",    Icon: Lightbulb },
    { name: "Rocket",        label: "Nâng cao",   Icon: Rocket },
    { name: "BookMarked",    label: "Đánh dấu",   Icon: BookMarked },
    { name: "Sparkles",      label: "Đặc biệt",   Icon: Sparkles },
    { name: "Palette",       label: "Sáng tạo",   Icon: Palette },
    { name: "Globe",         label: "Toàn cầu",   Icon: Globe },
    { name: "Music",         label: "Âm nhạc",    Icon: Music },
    { name: "Code2",         label: "Lập trình",  Icon: Code2 },
    { name: "Microscope",    label: "Khoa học",   Icon: Microscope },
];
